# Generated by Django 3.2.15 on 2023-04-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='postit',
            name='descricao',
            field=models.CharField(max_length=250, verbose_name='descricao_postit'),
        ),
    ]
